
# SEO settings
title: "Antoine Bolvy"
description: "Personal webpage."
keywords: "antoine, bolvy, saveman71, blog, personal, website, technology"
url: https://saveman71.com/ # site url
# baseurl: "/" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-42188815-1
repo: http://github.com/saveman71/saveman71.com
disqus_shortname: "saveman71"
twitter_username: "saveman71"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Antoine Bolvy"
  job      : "Student & Freelance Software Engineer"
  mission  : "well determined in changing the world, one line of code at a time"
  thumb    : /images/author.jpg
  email    : antoine.bolvy@gmail.com
  url      : https://saveman71.com
  github   : https://github.com/saveman71
  twitter  : https://twitter.com/Saveman71
  reddit   : https://reddit.com/u/Saveman71
  facebook : https://www.facebook.com/saveman71
  linkedin : https://linkedin.com/in/antoiebolvy

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@Saveman71"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : /
    title: Home
  - slug : about
    title: About

exclude: ["gulp", "node_modules", "bower", "bower_components", "vendor", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
